### ISSUE TITLE
FOrigin don't need to be protected

### ISSUE THREAD

**Issue by mdbs99** [nunopicado/FastDecorators#1]
I believe FOrigin could be private.
All decorables only need to call `inherited` and don't need to see `FOrigin`.

https://github.com/nunopicado/FastDecorators/blob/695f295d4056decc65ea05c836cfbec5f1962350/FooIntf.pas#L13

**Comment by nunopicado** [comment]
Yes, I think you are right. 
Even if a new constructor needs to be created for the decorator, it can just call the original Create method inside.
